
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.border.EtchedBorder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vinícius Alves de Campos
 */
public class calculadora extends javax.swing.JFrame {

    double num1, num2, resultado, contador=0; //CRIAÇÃO DAS VARIAVEIS TIPO DOUBLE.
    char operacao; //CRIAÇÃO DA VARIAVEL TIPO CHAR.
    
    
    public calculadora() {
        initComponents();
        this.setLocationRelativeTo(null); //CODIGO PARA A CALCULADORA ABRIR NO MEIO DA TELA.
        jPanel1.setFocusable(true); //CODIGO PARA O FOCO IR PRO JPANEL QUANDO A CALCULADORA FOR ACIONADA.
        incrementarIcone(); //CODIGO PARA INCREMENTAR O ICONE NA BARRA SUPERIOR.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        lblIcon = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTela = new javax.swing.JLabel();
        btn7 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnPonto = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btnMult = new javax.swing.JButton();
        btnMenos = new javax.swing.JButton();
        btnMais = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnRaiz = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblTemp = new javax.swing.JLabel();
        btnMaisMenos = new javax.swing.JButton();

        jButton5.setText("jButton1");

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        lblTela.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        lblTela.setForeground(new java.awt.Color(255, 255, 255));
        lblTela.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTela.setText("0");

        btn7.setBackground(new java.awt.Color(204, 204, 204));
        btn7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn7.setText("7");
        btn7.setBorderPainted(false);
        btn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn7MouseExited(evt);
            }
        });
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(204, 204, 204));
        btn4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn4.setText("4");
        btn4.setBorderPainted(false);
        btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn4MouseExited(evt);
            }
        });
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn1.setBackground(new java.awt.Color(204, 204, 204));
        btn1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn1.setText("1");
        btn1.setBorderPainted(false);
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn1MouseExited(evt);
            }
        });
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btnC.setBackground(new java.awt.Color(153, 153, 153));
        btnC.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnC.setText("C");
        btnC.setBorderPainted(false);
        btnC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCMouseExited(evt);
            }
        });
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(204, 204, 204));
        btn8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn8.setText("8");
        btn8.setBorderPainted(false);
        btn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn8MouseExited(evt);
            }
        });
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(204, 204, 204));
        btn5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn5.setText("5");
        btn5.setBorderPainted(false);
        btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn5MouseExited(evt);
            }
        });
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(204, 204, 204));
        btn2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn2.setText("2");
        btn2.setBorderPainted(false);
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn2MouseExited(evt);
            }
        });
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn0.setBackground(new java.awt.Color(204, 204, 204));
        btn0.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn0.setText("0");
        btn0.setBorderPainted(false);
        btn0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn0MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn0MouseExited(evt);
            }
        });
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(204, 204, 204));
        btn9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn9.setText("9");
        btn9.setBorderPainted(false);
        btn9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn9MouseExited(evt);
            }
        });
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(204, 204, 204));
        btn6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn6.setText("6");
        btn6.setBorderPainted(false);
        btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn6MouseExited(evt);
            }
        });
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(204, 204, 204));
        btn3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn3.setText("3");
        btn3.setBorderPainted(false);
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn3MouseExited(evt);
            }
        });
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btnPonto.setBackground(new java.awt.Color(153, 153, 153));
        btnPonto.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnPonto.setText(".");
        btnPonto.setBorderPainted(false);
        btnPonto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPontoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPontoMouseExited(evt);
            }
        });
        btnPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPontoActionPerformed(evt);
            }
        });

        btnDiv.setBackground(new java.awt.Color(255, 204, 51));
        btnDiv.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnDiv.setText("/");
        btnDiv.setBorderPainted(false);
        btnDiv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDivMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDivMouseExited(evt);
            }
        });
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });

        btnMult.setBackground(new java.awt.Color(255, 204, 51));
        btnMult.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnMult.setText("x");
        btnMult.setBorderPainted(false);
        btnMult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMultMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMultMouseExited(evt);
            }
        });
        btnMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultActionPerformed(evt);
            }
        });

        btnMenos.setBackground(new java.awt.Color(255, 204, 51));
        btnMenos.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnMenos.setText("-");
        btnMenos.setBorderPainted(false);
        btnMenos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenosMouseExited(evt);
            }
        });
        btnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosActionPerformed(evt);
            }
        });

        btnMais.setBackground(new java.awt.Color(255, 204, 51));
        btnMais.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnMais.setText("+");
        btnMais.setBorderPainted(false);
        btnMais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMaisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMaisMouseExited(evt);
            }
        });
        btnMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaisActionPerformed(evt);
            }
        });

        btnIgual.setBackground(new java.awt.Color(255, 204, 51));
        btnIgual.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnIgual.setText("=");
        btnIgual.setBorderPainted(false);
        btnIgual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIgualMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIgualMouseExited(evt);
            }
        });
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });

        btnRaiz.setBackground(new java.awt.Color(255, 204, 51));
        btnRaiz.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnRaiz.setText("√");
        btnRaiz.setBorderPainted(false);
        btnRaiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRaizMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRaizMouseExited(evt);
            }
        });
        btnRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaizActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 204, 51));
        btnBack.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnBack.setText("<- Backspace");
        btnBack.setBorderPainted(false);
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTemp.setForeground(new java.awt.Color(255, 255, 255));
        lblTemp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        btnMaisMenos.setBackground(new java.awt.Color(255, 204, 51));
        btnMaisMenos.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnMaisMenos.setText("+ -");
        btnMaisMenos.setBorderPainted(false);
        btnMaisMenos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMaisMenosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMaisMenosMouseExited(evt);
            }
        });
        btnMaisMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaisMenosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTemp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn4)
                                            .addComponent(btn1)
                                            .addComponent(btnC))
                                        .addGap(5, 5, 5)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn0)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(btn2)
                                                .addComponent(btn5)))
                                        .addGap(5, 5, 5))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnPonto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMaisMenos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnMult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMais, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn1, btn2, btn3, btn4, btn5, btn6, btn7, btn8, btn9});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lblTela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn7)
                            .addComponent(btn8)
                            .addComponent(btn9)
                            .addComponent(btnDiv))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn4)
                            .addComponent(btn5)
                            .addComponent(btn6)
                            .addComponent(btnMult, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnMais, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn1)
                            .addComponent(btn2)
                            .addComponent(btn3)
                            .addComponent(btnMenos)
                            .addComponent(btnRaiz))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnC)
                            .addComponent(btn0)
                            .addComponent(btnPonto)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnMaisMenos)))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnBack)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblTela, lblTemp});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn1, btn2, btn3, btn4, btn5, btn6, btn7, btn8, btn9});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        setarNumerosLbTela('5'); //CHAMADA DO METODO SETARNUMEROSLBTELA() PARA INCREMENTAR O NUMERO DIGITADO NA TELA.
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        setarNumerosLbTela('1'); //CHAMADA DO METODO SETARNUMEROSLBTELA() PARA INCREMENTAR O NUMERO DIGITADO NA TELA.
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        setarNumerosLbTela('2'); //CHAMADA DO METODO SETARNUMEROSLBTELA() PARA INCREMENTAR O NUMERO DIGITADO NA TELA.
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        setarNumerosLbTela('3'); //CHAMADA DO METODO SETARNUMEROSLBTELA() PARA INCREMENTAR O NUMERO DIGITADO NA TELA.
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        setarNumerosLbTela('4'); //CHAMADA DO METODO SETARNUMEROSLBTELA() PARA INCREMENTAR O NUMERO DIGITADO NA TELA.
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        setarNumerosLbTela('6'); //CHAMADA DO METODO SETARNUMEROSLBTELA() PARA INCREMENTAR O NUMERO DIGITADO NA TELA.
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        setarNumerosLbTela('7'); //CHAMADA DO METODO SETARNUMEROSLBTELA() PARA INCREMENTAR O NUMERO DIGITADO NA TELA.
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        setarNumerosLbTela('8'); //CHAMADA DO METODO SETARNUMEROSLBTELA() PARA INCREMENTAR O NUMERO DIGITADO NA TELA.
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        setarNumerosLbTela('9'); //CHAMADA DO METODO SETARNUMEROSLBTELA() PARA INCREMENTAR O NUMERO DIGITADO NA TELA.
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        setarNumerosLbTela('0'); //CHAMADA DO METODO SETARNUMEROSLBTELA() PARA INCREMENTAR O NUMERO DIGITADO NA TELA.
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPontoActionPerformed
        setarNumerosLbTela('.');  //CHAMADA DO METODO SETARNUMEROSLBTELA() PARA INCREMENTAR O PONTO NA TELA.
        btnPonto.setEnabled(false); //CODIGO PARA QUE O PONTO SEJA DESATIVADO APÓS SER DIGITADO UMA VEZ. EVITANDO ERROS.
    }//GEN-LAST:event_btnPontoActionPerformed

    private void btnMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaisActionPerformed
        pegarNum1(); //CHAMADA DO METODO PEGARNUM1() PARA PEGAR O PRIMEIRO NUMERO DIGITADO.
        operacao='+'; //CODIGO PARA IDENTIFICAR A OPERACAO A SER REALIZADA.
        setarValoresLbTemp(); //CHAMADA DO METODO SETARVALORESLBTEMP() PARA SETAR OS NUMEROS NO LBLTEMP.
    }//GEN-LAST:event_btnMaisActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        pegarNum1(); //CHAMADA DO METODO PEGARNUM1() PARA PEGAR O PRIMEIRO NUMERO DIGITADO.
        operacao='/'; //CODIGO PARA IDENTIFICAR A OPERACAO A SER REALIZADA.
        setarValoresLbTemp(); //CHAMADA DO METODO SETARVALORESLBTEMP() PARA SETAR OS NUMEROS NO LBLTEMP.
    }//GEN-LAST:event_btnDivActionPerformed

    private void btnMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultActionPerformed
        pegarNum1(); //CHAMADA DO METODO PEGARNUM1() PARA PEGAR O PRIMEIRO NUMERO DIGITADO.
        operacao='*'; //CODIGO PARA IDENTIFICAR A OPERACAO A SER REALIZADA.
        setarValoresLbTemp(); //CHAMADA DO METODO SETARVALORESLBTEMP() PARA SETAR OS NUMEROS NO LBLTEMP.
    }//GEN-LAST:event_btnMultActionPerformed

    private void btnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosActionPerformed
        pegarNum1(); //CHAMADA DO METODO PEGARNUM1() PARA PEGAR O PRIMEIRO NUMERO DIGITADO.
        operacao='-'; //CODIGO PARA IDENTIFICAR A OPERACAO A SER REALIZADA.
        setarValoresLbTemp(); //CHAMADA DO METODO SETARVALORESLBTEMP() PARA SETAR OS NUMEROS NO LBLTEMP.
    }//GEN-LAST:event_btnMenosActionPerformed

    private void btnRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaizActionPerformed
        pegarNum1(); //CHAMADA DO METODO PEGARNUM1() PARA PEGAR O PRIMEIRO NUMERO DIGITADO.
        operacao='√'; //CODIGO PARA IDENTIFICAR A OPERACAO A SER REALIZADA.
        calcular(); //CHAMADA DO METODO CALCULAR() PARA CALCULAR OS NÚMEROS DE ACORDO COM SUA OPERACAO.
        setarValoresLbTemp(); //CHAMADA DO METODO SETARVALORESLBTEMP() PARA SETAR OS NUMEROS NO LBLTEMP.
    }//GEN-LAST:event_btnRaizActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        
        //CONDIÇÃO UTILIZADA PARA QUE SEJA POSSIVEL REALIZAR DUAS OU MAIS OPERAÇÕES APENAS APERTANDO = DUAS VEZES.
        if(contador==0){
            pegarNum2(); //CHAMADA DO METODO PEGARNUM2() PARA PEGAR O SEGUNDO NUMERO DIGITADO.
            calcular(); //CHAMADA DO METODO CALCULAR() PARA CALCULAR OS NÚMEROS DE ACORDO COM SUA OPERACAO.
            lblTemp.setText(lblTemp.getText() + " " + num2 + " ="); //CODIGO PARA INCREMENTAR O SEGUNDO NUMERO DIGITADO JUNTO AO PRIMEIRO + A SUA OPERAÇÃO NO LBLTEMP.
        }else{
            calcular(); //CHAMADA DO METODO CALCULAR() PARA CALCULAR OS NÚMEROS DE ACORDO COM SUA OPERACAO.
            lblTemp.setText(num1+ " " + operacao + " " + num2 + " ="); //CODIGO PARA INCREMENTAR O SEGUNDO NUMERO DIGITADO JUNTO AO PRIMEIRO + A SUA OPERAÇÃO NO LBLTEMP.
        }
        contador++; // INCREMENTADOR DA VARIAVEL CONTADOR.
    }//GEN-LAST:event_btnIgualActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        reiniciarCalculadora(); // CHAMADA DA FUNCAO REINICIARCALCULADORA() RESPONSÁVEL POR ZERAR O NÚMERO DAS VARIAVEIS E LIMPAR TODOS OS CAMPOS.
        jPanel1.requestFocus(); // FOCO É RETORNADO PARA O JPANEL PARA QUE SEJA POSSIVEL DIGITAR COM O TECLADO.
        btnPonto.setEnabled(true); // O BOTÃO DO PONTO É ATIVADO NOVAMENTE.
    }//GEN-LAST:event_btnCActionPerformed


    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        backspace(); // CHAMADA DA FUNÇÃO BACKSPACE PARA QUE SEJA REMOVIDO O ULTIMO NÚMERO DO LBLTELA.
    }//GEN-LAST:event_btnBackActionPerformed


    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        //CONDICAO PARA VERIFICAR SE É UM NUMERO DIGITADO/IGUAL OU BACKSPACE.
        if(evt.getKeyChar()=='0' ||
           evt.getKeyChar()=='1' ||
           evt.getKeyChar()=='2' ||
           evt.getKeyChar()=='3' ||
           evt.getKeyChar()=='4' ||
           evt.getKeyChar()=='5' ||
           evt.getKeyChar()=='6' ||     
           evt.getKeyChar()=='7' ||
           evt.getKeyChar()=='8' ||
           evt.getKeyChar()=='9')
        {
           setarNumerosLbTela(evt.getKeyChar()); //CHAMADA DO METODO SETARNUMEROSLBTELA() PARA VERIFICAR O NUMERO DIGITADO E INSERIR NO LBLTELA.
        }else if(evt.getKeyChar() == '-' ||
                 evt.getKeyChar() == '+' ||
                 evt.getKeyChar() == '/' ||
                 evt.getKeyChar() == '*'){
            pegarNum1(); // CHAMADA DO METODO PEGARNUM1() RESPONSÁVEL POR PEGAR O PRIMEIRO NUMERO E ATRIBUIR NA VARIAVEL NUM1;
            operacao = evt.getKeyChar(); //CODIGO PARA VERIFICAR A OPERAÇÃO QUE FOI DIGITADA.
            setarValoresLbTemp(); //CHAMADA DO MEOTOD SETARVALORESLBTEMP() PARA QUE O NÚMERO DIGITADO SEJA INSERIDO NO LBLTEMP.
        }else if(evt.getKeyCode()==10){
            //CONDIÇÃO UTILIZADA PARA QUE SEJA POSSIVEL REALIZAR DUAS OU MAIS OPERAÇÕES APENAS APERTANDO = DUAS VEZES.
            if(contador==0){
                pegarNum2(); //CHAMADA DO METODO PEGARNUM2() PARA PEGAR O SEGUNDO NUMERO DIGITADO.
                calcular(); //CHAMADA DO METODO CALCULAR() PARA CALCULAR OS NÚMEROS DE ACORDO COM SUA OPERACAO.
                lblTemp.setText(num1+ " " + operacao + " " + num2 + " ="); //CODIGO PARA INCREMENTAR O SEGUNDO NUMERO DIGITADO JUNTO AO PRIMEIRO + A SUA OPERAÇÃO NO LBLTEMP.
              }else{
                calcular(); //CHAMADA DO METODO CALCULAR() PARA CALCULAR OS NÚMEROS DE ACORDO COM SUA OPERACAO.
                lblTemp.setText(num1+ " " + operacao + " " + num2 + " ="); //CODIGO PARA INCREMENTAR O SEGUNDO NUMERO DIGITADO JUNTO AO PRIMEIRO + A SUA OPERAÇÃO NO LBLTEMP.
              }
              contador++;
        }else if(evt.getKeyCode()==8){
            backspace(); // CHAMADA DA FUNÇÃO BACKSPACE PARA QUE SEJA REMOVIDO O ULTIMO NÚMERO DO LBLTELA.
        }
        
    }//GEN-LAST:event_jPanel1KeyPressed

    private void btnMaisMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaisMenosActionPerformed
        //String numero = lblTela.getText();
        double num = Double.parseDouble(lblTela.getText()); //CRIAÇÃO DE UMA VARIAVEL CHAMADA 'NUM' DO TIPO 'DOUBLE' E ATRIBUIÇÃO A MESMA COM O VALOR QUE ESTA PRESENTE NO LBLTELA.
        
        //CONDICAO PARA VERIFICAR SE A VARIAVEL NUM É DIFERENTE DE 0, POIS 0 NÃO PODE SER NEGATIVO.
        if(num!=0){
            num = num * -1; //OPERAÇÃO PARA QUE O SINAL DO NÚMERO SEJA INVERTIDO.
            lblTela.setText(String.valueOf(num)); //CODIGO PARA SETAR O NUMERO NO LBLTELA.
        }
        jPanel1.requestFocus(); //CODIGO PARA QUE O FOCO VOLTE PARA O JPANEL.
        
    }//GEN-LAST:event_btnMaisMenosActionPerformed

    private void btn7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn7MouseEntered
        btn7.setBackground(new Color(153,153,153)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE ESTIVER SOBRE O MESMO.
    }//GEN-LAST:event_btn7MouseEntered

    private void btn7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn7MouseExited
        btn7.setBackground(new Color(204,204,204)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE NÃO ESTIVER MAIS SOBRE O MESMO.
    }//GEN-LAST:event_btn7MouseExited

    private void btn8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MouseEntered
        btn8.setBackground(new Color(153,153,153)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE ESTIVER SOBRE O MESMO.
    }//GEN-LAST:event_btn8MouseEntered

    private void btn8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MouseExited
        btn8.setBackground(new Color(204,204,204)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE NÃO ESTIVER MAIS SOBRE O MESMO.
    }//GEN-LAST:event_btn8MouseExited

    private void btn9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn9MouseEntered
        btn9.setBackground(new Color(153,153,153)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE ESTIVER SOBRE O MESMO.
    }//GEN-LAST:event_btn9MouseEntered

    private void btn9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn9MouseExited
        btn9.setBackground(new Color(204,204,204)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE NÃO ESTIVER MAIS SOBRE O MESMO.
    }//GEN-LAST:event_btn9MouseExited

    private void btn4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseEntered
        btn4.setBackground(new Color(153,153,153)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE ESTIVER SOBRE O MESMO.
    }//GEN-LAST:event_btn4MouseEntered

    private void btn4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseExited
        btn4.setBackground(new Color(204,204,204)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE NÃO ESTIVER MAIS SOBRE O MESMO.
    }//GEN-LAST:event_btn4MouseExited

    private void btn5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseEntered
        btn5.setBackground(new Color(153,153,153)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE ESTIVER SOBRE O MESMO.
    }//GEN-LAST:event_btn5MouseEntered

    private void btn5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseExited
        btn5.setBackground(new Color(204,204,204)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE NÃO ESTIVER MAIS SOBRE O MESMO.
    }//GEN-LAST:event_btn5MouseExited

    private void btn6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MouseEntered
        btn6.setBackground(new Color(153,153,153)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE ESTIVER SOBRE O MESMO.
    }//GEN-LAST:event_btn6MouseEntered

    private void btn6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MouseExited
        btn6.setBackground(new Color(204,204,204)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE NÃO ESTIVER MAIS SOBRE O MESMO.
    }//GEN-LAST:event_btn6MouseExited

    private void btn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseEntered
        btn1.setBackground(new Color(153,153,153)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE ESTIVER SOBRE O MESMO.
    }//GEN-LAST:event_btn1MouseEntered

    private void btn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseExited
        btn1.setBackground(new Color(204,204,204)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE NÃO ESTIVER MAIS SOBRE O MESMO.
    }//GEN-LAST:event_btn1MouseExited

    private void btn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseExited
        btn2.setBackground(new Color(204,204,204)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE NÃO ESTIVER MAIS SOBRE O MESMO.
    }//GEN-LAST:event_btn2MouseExited

    private void btn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseExited
        btn3.setBackground(new Color(204,204,204)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE NÃO ESTIVER MAIS SOBRE O MESMO.
    }//GEN-LAST:event_btn3MouseExited

    private void btn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseEntered
        btn2.setBackground(new Color(153,153,153)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE ESTIVER SOBRE O MESMO.
    }//GEN-LAST:event_btn2MouseEntered

    private void btn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseEntered
        btn3.setBackground(new Color(153,153,153)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE ESTIVER SOBRE O MESMO.
    }//GEN-LAST:event_btn3MouseEntered

    private void btn0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn0MouseEntered
        btn0.setBackground(new Color(153,153,153)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE ESTIVER SOBRE O MESMO.
    }//GEN-LAST:event_btn0MouseEntered

    private void btn0MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn0MouseExited
        btn0.setBackground(new Color(204,204,204)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE NÃO ESTIVER MAIS SOBRE O MESMO.
    }//GEN-LAST:event_btn0MouseExited

    private void btnDivMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDivMouseEntered
        btnDiv.setBackground(new Color(255,224,132)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE ESTIVER SOBRE O MESMO.
    }//GEN-LAST:event_btnDivMouseEntered

    private void btnDivMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDivMouseExited
        btnDiv.setBackground(new Color(255,204,51)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE NÃO ESTIVER MAIS SOBRE O MESMO.
    }//GEN-LAST:event_btnDivMouseExited

    private void btnMaisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaisMouseEntered
        btnMais.setBackground(new Color(255,224,132)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE ESTIVER SOBRE O MESMO.
    }//GEN-LAST:event_btnMaisMouseEntered

    private void btnMultMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMultMouseEntered
        btnMult.setBackground(new Color(255,224,132)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE ESTIVER SOBRE O MESMO.
    }//GEN-LAST:event_btnMultMouseEntered

    private void btnMenosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenosMouseEntered
        btnMenos.setBackground(new Color(255,224,132)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE ESTIVER SOBRE O MESMO.
    }//GEN-LAST:event_btnMenosMouseEntered

    private void btnRaizMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRaizMouseEntered
        btnRaiz.setBackground(new Color(255,224,132)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE ESTIVER SOBRE O MESMO.
    }//GEN-LAST:event_btnRaizMouseEntered

    private void btnMaisMenosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaisMenosMouseEntered
        btnMaisMenos.setBackground(new Color(255,224,132)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE ESTIVER SOBRE O MESMO.
    }//GEN-LAST:event_btnMaisMenosMouseEntered

    private void btnIgualMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIgualMouseEntered
        btnIgual.setBackground(new Color(255,224,132)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE NÃO ESTIVER MAIS SOBRE O MESMO.
    }//GEN-LAST:event_btnIgualMouseEntered

    private void btnIgualMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIgualMouseExited
        btnIgual.setBackground(new Color(255,204,51)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE NÃO ESTIVER MAIS SOBRE O MESMO.
    }//GEN-LAST:event_btnIgualMouseExited

    private void btnMaisMenosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaisMenosMouseExited
        btnMaisMenos.setBackground(new Color(255,204,51)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE NÃO ESTIVER MAIS SOBRE O MESMO.
    }//GEN-LAST:event_btnMaisMenosMouseExited

    private void btnMenosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenosMouseExited
        btnMenos.setBackground(new Color(255,204,51)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE NÃO ESTIVER MAIS SOBRE O MESMO.
    }//GEN-LAST:event_btnMenosMouseExited

    private void btnRaizMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRaizMouseExited
        btnRaiz.setBackground(new Color(255,204,51)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE NÃO ESTIVER MAIS SOBRE O MESMO.
    }//GEN-LAST:event_btnRaizMouseExited

    private void btnMaisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaisMouseExited
        btnMais.setBackground(new Color(255,204,51)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE NÃO ESTIVER MAIS SOBRE O MESMO.
    }//GEN-LAST:event_btnMaisMouseExited

    private void btnMultMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMultMouseExited
        btnMult.setBackground(new Color(255,204,51)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE NÃO ESTIVER MAIS SOBRE O MESMO.
    }//GEN-LAST:event_btnMultMouseExited

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        btnBack.setBackground(new Color(255,224,132)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE ESTIVER SOBRE O MESMO.
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        btnBack.setBackground(new Color(255,204,51)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE NÃO ESTIVER MAIS SOBRE O MESMO.
    }//GEN-LAST:event_btnBackMouseExited

    private void btnCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCMouseExited
        btnC.setBackground(new Color(153,153,153)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE NÃO ESTIVER MAIS SOBRE O MESMO.
    }//GEN-LAST:event_btnCMouseExited

    private void btnPontoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPontoMouseExited
        btnPonto.setBackground(new Color(153,153,153)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE NÃO ESTIVER MAIS SOBRE O MESMO.
    }//GEN-LAST:event_btnPontoMouseExited

    private void btnCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCMouseEntered
        btnC.setBackground(new Color(204,204,204)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE ESTIVER SOBRE O MESMO.
    }//GEN-LAST:event_btnCMouseEntered

    private void btnPontoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPontoMouseEntered
        btnPonto.setBackground(new Color(204,204,204)); //CODIGO PARA QUE A COR DO BOTÃO SEJA MODIFICADA QUANDO O MOUSE ESTIVER SOBRE O MESMO.
    }//GEN-LAST:event_btnPontoMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMais;
    private javax.swing.JButton btnMaisMenos;
    private javax.swing.JButton btnMenos;
    private javax.swing.JButton btnMult;
    private javax.swing.JButton btnPonto;
    private javax.swing.JButton btnRaiz;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblTela;
    private javax.swing.JLabel lblTemp;
    // End of variables declaration//GEN-END:variables

    
    //METODO RESPONSÁVEL POR SETAR OS NUMEROS NO LBTELA.
     public void setarNumerosLbTela(char numero){

        if("0".equals(lblTela.getText()) && !".".equals(String.valueOf(numero))){
            lblTela.setText("");
        }
        
        String texto = lblTela.getText();
        
        if(texto.length()<=14){
            texto = texto+numero;
            lblTela.setText(texto);
            jPanel1.requestFocus();
        }
    }
    
     //METODO RESPONSAVEL POR ATRIBUIR O NUMERO DIGITADO A VARIAVEL 1.
    public void pegarNum1(){
        num1 = Double.parseDouble(lblTela.getText());
        lblTela.setText("0");
        jPanel1.requestFocus();
    }
    
    //METODO RESPONSAVEL POR ATRIBUIR O NUMERO DIGITADO A VARIAVEL 2.
    public void pegarNum2(){
        num2 = Double.parseDouble(lblTela.getText());
        lblTela.setText("");
        
    }
    
    //METODO RESPONSAVEL POR ATRIBUIR O NUMERO DIGITADO AO LBLTEMP.
    public void setarValoresLbTemp(){
            lblTemp.setText(num1 + " " +operacao);
    }
    
    //METODO RESPONSAVEL POR VERIFICAR A OPERAÇÃO SOLICITADA E REALIZAR COM BASE NOS DOIS NUMEROS DIGITADOS.
    public void calcular(){
        if(num2==0 && operacao=='/'){
            JOptionPane.showMessageDialog(null, "Operação inválida!"); 
            reiniciarCalculadora();
        }else{
            if(contador==0){
                if(operacao == '+'){
                    resultado = num1 + num2;
                }else if(operacao == '-'){
                    resultado = num1 - num2;
                }else if(operacao == '*'){
                    resultado = num1 * num2;
                }else if(operacao == '/'){
                    resultado = num1 / num2;
                }else{
                    resultado = Math.sqrt(num1);
                }
            }else{
                if(operacao == '+'){
                    num1 = resultado;
                    resultado = num1 + num2;
                }else if(operacao == '-'){
                    num1=resultado;
                    resultado = num1 - num2;
                }else if(operacao == '*'){
                    num1=resultado;
                    resultado = num1 * num2;
                }else if(operacao == '/'){
                    num1=resultado;
                    resultado = num1 / num2;
                }else{
                    resultado = Math.sqrt(num1);
                }
            }
        }

            lblTela.setText(String.valueOf(resultado));
            jPanel1.requestFocus();
    }
    
    //METODO PARA ZERAR TODA A CALCULADORA.
    public void reiniciarCalculadora() {
        num1 = 0;
        num2 = 0;
        resultado = 0;
        lblTela.setText("0");
        lblTemp.setText("");
        contador=0;
    }


    //METODO DA FUNÇÃO BACKSPACE: VOLTA UM NÚMERO.
    public void backspace() {
        String valor_lblTela = lblTela.getText();
        
        if(lblTela.getText().length()>1){
            
            if(".".equals(valor_lblTela.substring(valor_lblTela.length()-2, valor_lblTela.length()-1))){
                valor_lblTela = valor_lblTela.substring(0, valor_lblTela.length()-2);
                lblTela.setText(valor_lblTela);
            }else{
                valor_lblTela = valor_lblTela.substring(0, valor_lblTela.length()-1);
            }
            
            lblTela.setText(valor_lblTela);
            
        }else{
            lblTela.setText("0");
        }
        jPanel1.requestFocus();
    }
    
    //METODO PARA INCREMENTAR O ICONE NA BARRA SUPERIOR.
    private void incrementarIcone() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("calculator.png")));
    }
}
